### ISSUE TITLE
More Complete Examples for Semigroup and Semiring Validation

### ISSUE THREAD

**Issue by jkachmar** [purescript/purescript-validation#16]
I worked out some more complete examples of validations using the Semigroup and Semiring instances today. They're pretty opinionated, but I think having a more completely worked out example in the repository could help newcomers.

Right now they're in a separate repo [here](https://github.com/jkachmar/purescript-validation-experiment), but if this seems like something the maintainers would like, I can clean them up and put them into a proper PR.

**Comment by paf31** [comment]
I think it would be great to have an example project in this repo or in the README - thanks for putting this together!

It would be good to try to minimize the dependencies and code as much as possible, I think.

**Comment by jkachmar** [comment]
Yeah, the repo was a bit of a rabbit hole for me this weekend to get comfortable with the library 😅. 

I'll pare some stuff back and try to PR an example repo soon. I'm thinking an `examples` directory with a subdirectory for `semigroup-validation` and `semiring-validation` that would provide small, runnable examples that printed some successful/unsuccessful validation results to the console.

**Comment by jkachmar** [comment]
How does this look: https://github.com/jkachmar/purescript-validation/tree/feat/add-examples/examples/semigroup ?

If that's good, I can do something similar for `Semiring` and PR them both.

**Comment by chexxor** [comment]
Yeah, this library is frustrating af without a full-blown explanation of it.

It's questions like:

- How is different than using `Either`? (accumulating errors)
- Why one would want to accumulate errors?
- How is validation different than parsing? (parsing `Foreign` vs validating `EmailFormattedString`)
- Why not enforce a `NonEmpty` functor in the error side?
- How to build a big validator from small, reusable validators? (`v1 <> v2 *> resultVal`?)
- How to build small, reusable validators? (why use `Unit` as result?)
- What kinds of data types can a validator return? (`String` vs `EmailFormattedString`?)

Every time I use this library I get annoyed that I have to `validateX someVal *> pure someVal`, because `someVal` is duplicated, which is painful for me to see, and I hate using `pure` because for me it's a sign that I should just use `map`.

**Comment by hdgarrood** [comment]
#17 added examples for the Semiring version.

**Comment by JordanMartinez** [comment]
Closed by #17?

**Comment by hdgarrood** [comment]
This should not be considered closed by #17; that PR only added examples for semigroup validation. Semiring validation is still lacking documentation (although personally, I still think it doesn't deserve to be in core and we should solve that part of the problem by just removing it).
