### ISSUE TITLE
Export the V data constructor

### ISSUE THREAD

**Issue by gregberns** [purescript/purescript-validation#20]
If I try and create a Validator with the new type it doesn't recognize `V` as a data constructor.

```
--my module
import Data.Validation.Semigroup (V(..), V, invalid)

--Try to use it
valid :: forall err result. result -> V err result
valid = V <<< Right
```

Error: `Unknown data constructor V`

I'm new to PS, but this article seems to say that `V` needs to be exported from the Validation lib like `V(..)` to be able to use it.
https://stackoverflow.com/questions/47677049/importing-newtypes-from-another-module

Am I missing something?

**Comment by thomashoneyman** [comment]
If I remember correctly, this library intentionally hides the `V` data constructor to implement the [smart constructor pattern](https://thomashoneyman.com/guides/real-world-halogen/design-data-pure-functions/#restricting-the-domain-using-smart-constructors). But since it exposes...

- `invalid` to construct errors
- `unV` to handle the error result from a `V` type, to allow pseudo-pattern matching
- `pure` (from the `Applicative` class)

...I'm not really sure what's being gained by hiding the constructor. Unless that's changed, you can always use `pure` instead of the constructor explicitly:

```purescript
valid :: forall err res. Semigroup err => res -> V err res
valid = pure
```

**Comment by gregberns** [comment]
Thanks for taking a look @thomashoneyman. If I import `import Control.Applicative (pure)` then I get this error in that `valid` example. Does that relate to issue #14? Seems to be what they're discussing.

```
No type class instance was found for

    Data.Semigroup.Semigroup err1
```

**Comment by thomashoneyman** [comment]
You should be fine if you add a `Semigroup` constraint to your error type. The `Data.Validation.Semigroup` module collects errors as a side effect of `apply`, relying on the `Semigroup` instance to aggregate the errors. 

#14 is about the same thing; it doesn't seem strictly necessary for this function to have the constraint, but as Phil noted, there's not much sense in using the library if you aren't using a semigroup / semiring to collect errors using the `Applicative` instance.

As far as your error there, I think it's because you say your `decode` function is creating something of type

```purescript
decode :: List String -> V (Array ParseError) String
```

but then you provide it with a `Right ""`, which has a different type altogether:

```purescript
decode :: forall e. List String -> V (Array ParseError) (Either e String)
decode _ = pure $ Right ""
```

Try just using `pure ""` instead if the result is meant to be a `String`. Here's a longer example:

```purescript
module Main where

import Prelude

import Data.Traversable (traverse_)
import Data.Validation.Semigroup (V, unV)
import Effect (Effect)
import Effect.Console as Console

main :: Effect Unit
main = res

valid :: forall err res. Semigroup err => res -> V err res
valid = pure

decode :: Array String -> V (Array String) String
decode _ = pure "Success!"

res :: Effect Unit
res =
  unV
    (traverse_ (Console.log <<< append "error! "))
    (Console.log <<< append "success! ")
    (decode ["my", "string", "test" ])
```
